version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=verano
      - MYSQL_DATABASE=fantasy
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=verano
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/fantasy.sql:/docker-entrypoint-initdb.d/01_fantasy.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=admin
      - PMA_PASSWORD=verano
      - UPLOAD_LIMIT=128M
    ports:
      - "8091:80"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8090:80"
    volumes:
      - ./app:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

